### ISSUE TITLE
Trouble building

### ISSUE THREAD

**Issue by petergdoyle** [sutoiku/node-kafka#5]
I have tried tried this several times on a CentOS 7 official docker image. I installed Node.js and tried to install the other packages needed and still get errors in the build. 
Here is what is installed on the clean CentOS 7 box 
```console
[root@6d8d5e76d1de node-kafka]# yum -y install epel-release
[root@6d8d5e76d1de node-kafka]# yum -y install nodejs npm 
[root@6d8d5e76d1de node-kafka]# npm install node-gyp
[root@6d8d5e76d1de node-kafka]# npm update -g node-gyp 
[root@6d8d5e76d1de node-kafka]# node --version
v0.10.36
[root@6d8d5e76d1de node-kafka]# npm --version
1.3.6
[root@6d8d5e76d1de node-kafka]# node-gyp --version
v3.0.3
[root@6d8d5e76d1de node-kafka]# make --version
GNU Make 3.82
Built for x86_64-redhat-linux-gnu
```

And I continue to get build errors 
```console
[root@6d8d5e76d1de node-kafka]# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@3.0.3
gyp info using node@0.10.36 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/node-kafka/build'
make: *** No rule to make target `../../usr/lib/node_modules/node-gyp/addon-rpm.gypi', needed by `Makefile'.  Stop.
make: Leaving directory `/node-kafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-229.11.1.el7.x86_64
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /node-kafka
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
```

I would like to give this library a try for performance reasons but cannot. Any help would be appreciated. Thanks!

**Comment by psq** [comment]
I'm not familiar with this error, but this looks this could be a node-gyp issue.  Is there a reference to `addon-rpm.gypi` in the generated `Makefile` under the `build` directory?
Also, do you have `gcc` installed?

**Comment by petergdoyle** [comment]
Hey thanks for responding... 
I am build this on a base dockerized CentOS images, but I can reproduce it on the official Node docker image, and the base Ubuntu image as well. 
I do believe something is missing or out of sync and would like to help track it down and add something to this effort, so:
Here is the minimal Docker image with all required os and node packages installed (I believe)  [Dockerfile](https://github.com/petergdoyle/docker-images/blob/master/centos/7-node-kafka/Dockerfile)

if you create that docker image - ```docker build -t="petergdoyle/centos:node-kafka" . ```, 
and create a container from that image - ```docker run --rm -t -i "petergdoyle/centos:node-kafka"```, 
then clone node-kafka and try to build, this is what I get. 

I don't see a generated Makefile, and it looks like a c header file is missing or something.

```javascript
[root@fc7177340f56 node-kafka]# node-gyp configure
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.36 | linux | x64
gyp info spawn python
gyp info spawn args [ '/usr/bin/gyp',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/node-kafka/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/node-gyp/addon-rpm.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/share/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/usr/share/node',
gyp info spawn args   '-Dmodule_root_dir=/node-kafka',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info ok 
[root@fc7177340f56 node-kafka]# node-gyp build
gyp info it worked if it ends with ok
gyp info using node-gyp@0.10.6
gyp info using node@0.10.36 | linux | x64
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory `/node-kafka/build'
  CXX(target) Release/obj.target/librdkafkaBinding/src/kafka.o
../src/kafka.cc:11:34: fatal error: librdkafka/rdkafka.h: No such file or directory
   #include <librdkafka/rdkafka.h>
                                  ^
compilation terminated.
make: *** [Release/obj.target/librdkafkaBinding/src/kafka.o] Error 1
make: Leaving directory `/node-kafka/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.10.0-229.14.1.el7.x86_64
gyp ERR! command "node" "/usr/bin/node-gyp" "build"
gyp ERR! cwd /node-kafka
gyp ERR! node -v v0.10.36
gyp ERR! node-gyp -v v0.10.6
gyp ERR! not ok 

```

**Comment by petergdoyle** [comment]
Here is the Makefile that is generated https://gist.github.com/petergdoyle/c6dcea4d7ee743d80750

**Comment by psq** [comment]
this error is different, and you probably need to install the package for librdkafka.  on ubuntu, it looks like it is `librdkafka-dev` and `librdkafka1`, and there is a CentOS rpm available here at least (http://pkgs.org/centos-6/remi-x86_64/librdkafka-devel-0.8.6-1.el6.remi.x86_64.rpm.html and http://pkgs.org/centos-6/remi-x86_64/librdkafka-0.8.6-1.el6.remi.x86_64.rpm.html).  I haven't tried these, though.

As for the original error, the generated makefile includes a reference to `../../usr/lib/node_modules/node-gyp/addon-rpm.gypi`, maybe either the relative path is incorrect, or the file is really not there.  It that helps, that file is not part of my setup, but the generated `Makefile` includes absolute paths and only a reference to addon.gypi.  So perhaps you need to figure out why it uses relative paths?

**Comment by petergdoyle** [comment]
So what is your setup that you are getting this to build on? OS, node version, node-gyp version, etc. 
Thanks!

**Comment by psq** [comment]
Keep in mind it does not build with latest node versions (incompatible changes in V8 does no one has fixed yet).

my working setup:
OS: Mac OS 10.10.5
node: v0.10.40
npm: 2.14.4
node-gyp: v3.0.3

building with `npm install`
