### ISSUE TITLE
librdkafka/rdkafka.h file not found

### ISSUE THREAD

**Issue by sarpdoruk** [sutoiku/node-kafka#6]
I get **librdkafka/rdkafka.h file not found** error when I try to install node-kafka. 

Here is the output;

```
CXX(target) Release/obj.target/librdkafkaBinding/src/kafka.o
../src/kafka.cc:11:12: fatal error: 'librdkafka/rdkafka.h' file not found
  #include <librdkafka/rdkafka.h>
           ^
1 error generated.
make: *** [Release/obj.target/librdkafkaBinding/src/kafka.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/sarp/Sites/oa/workers/kafka-to-dynamodb/node_modules/node-kafka
gyp ERR! node -v v6.1.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN onedio-analytics-kafka-to-dynamodb@1.0.0 No repository field.
npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/Cellar/node/6.1.0/bin/node" "/usr/local/bin/npm" "i" "-S" "node-kafka"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE

npm ERR! node-kafka@0.0.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-kafka@0.0.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-kafka package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-kafka
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-kafka
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sarp/Sites/oa/workers/kafka-to-dynamodb/npm-debug.log
```

**Comment by andela-anandaa** [comment]
Why was this closed with no reference at at all? @sarpdoruk

**Comment by psq** [comment]
did you install  librdkafka (0.8.3 is the last one known to work, both headers and libraries?)

**Comment by andela-anandaa** [comment]
@psq - No, makes sense, let me do that 👍
